name: Test
on: push
jobs:
  regression-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [14]
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Set up Playwright
        uses: microsoft/playwright-github-action@v1
      - name: Install dependencies
        run: npm ci
      - name: Run lint checks
        run: npm run lint
      - name: Run visual regression tests
        run: npm test
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: screenshots
          path: test/ci/screenshots/**/*
